# Generated by Django 5.1 on 2024-08-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_habit', models.CharField(max_length=200, verbose_name='место, в котором необходимо выполнять привычку')),
                ('time_habit', models.TimeField(help_text='HH:MM', verbose_name='время, когда необходимо выполнять привычку')),
                ('action_habit', models.CharField(max_length=350, verbose_name='действие, которое представляет собой привычка')),
                ('period', models.CharField(choices=[('daily', 'ежедневно'), ('monday', 'понедельник'), ('tuesday', 'вторник'), ('wednesday', 'среда'), ('thursday', 'четверг'), ('friday', 'пятница'), ('saturday', 'суббота'), ('sunday', 'воскресенье')], default='Ежедневно', max_length=20, verbose_name='периодичность выполнения привычки')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('reward', models.CharField(blank=True, max_length=300, null=True, verbose_name='вознаграждение')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='время на выполнение привычки')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('frequency', models.SmallIntegerField(default=1, help_text='Привычку выполнять каждые * дней', verbose_name='Периодичность привычки (дней)')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
