# Generated by Django 5.1 on 2024-08-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_habits', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='period',
        ),
    ]
